name: Export Marp Slides

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ibm-plex fonts-oflb-asana-math fonts-dejavu-core

      - name: Refresh font cache
        run: fc-cache -f

      - name: Export index.md to HTML and PDF
        run: |
          npx @marp-team/marp-cli@latest index.md --html --output index.html --allow-local-files --theme-set ./my_theme.css
          npx @marp-team/marp-cli@latest index.md --pdf --output index.pdf --allow-local-files --theme-set ./my_theme.css

      - name: Commit exported files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: export Marp slides"
          file_pattern: index.html index.pdf
